// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhTXylEqhUfjNPLA1EgAGrRfhVBgzOgnk',
    appId: '1:611460569844:web:a8304778ab926ee6b09ca1',
    messagingSenderId: '611460569844',
    projectId: 'meroio',
    authDomain: 'meroio.firebaseapp.com',
    storageBucket: 'meroio.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy4Zkvz4cRh0hJeChyo1k8Kn5hxX4X0A4',
    appId: '1:611460569844:android:63c444637d3950aab09ca1',
    messagingSenderId: '611460569844',
    projectId: 'meroio',
    storageBucket: 'meroio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuIoYix3IxUzgJ2sNQT2QmyjQZfw1B8-8',
    appId: '1:611460569844:ios:b72fcb28c4a55885b09ca1',
    messagingSenderId: '611460569844',
    projectId: 'meroio',
    storageBucket: 'meroio.appspot.com',
    iosBundleId: 'com.example.meroio',
  );
}
